### ISSUE TITLE
Bottle labels

### ISSUE THREAD

**Issue by mehavenuggets** [mehavenuggets/drinksim#3]
Every single lable

**Comment by mehavenuggets** [comment]
DONE LIST:
Rum (X)
Creme de mure (X)
Tequila (X)
Vodka (X)
Gin (X)
Champagne (X)
Blue curaçao (X)
Whiskey (X)
Brandy (X)
blue curaçao (X)
Crème de mure (X)
Cointreau (X)
Galliano (X)
Drambuie (X)
Amaretto (X)
Triple Sec (X)
Tonic (X)
syrup (X)
coconut cream (X)
Cock-a-Cola (X)
cranberry juice (X)
pineapple juice (X)
orange juice (X)
grapefruit juice (X)

**Comment by Owarice** [comment]
your mum
